### ISSUE TITLE
doesn't work with angular ngfor / ngif on it

### ISSUE THREAD

**Issue by matanabatian** [nicolafranchini/VenoBox#143]

**Comment by msaqibaziz** [comment]
Resolved !
I had the same problem. I was running venobox on dynamic data coming from API. And Implemented ngFor on dynamic data coming from the API. It wasn't working because I was initializing VenoBox in ngAfterViewInit.
Solution is to initialize it after getting the data from API.
$(document).ready(function() {
      $('.venobox').venobox();
});
