### ISSUE TITLE
Animation

### ISSUE THREAD

**Issue by viliusle** [nicolafranchini/VenoBox#164]
1. Default animation takes almost 1 second to load next image, even it is already cached, should 100ms or 150ms. Right now it is very very slow.
2. There is no documentation about how to disable animation or change speed.

**Comment by nicolafranchini** [comment]
Default animation takes 500 milliseconds to fade-in, then loads the next content, then 500 milliseconds to fade-out.
You can inspect the uncompressed file venobox.js and edit the 2 respective functions: `content.animate`.
I can't exclude adding a new option for a custom duration.

**Comment by nicolafranchini** [comment]
Check the latest release, there is the new option `navSpeed`

**Comment by viliusle** [comment]
So use has to wait 1 second to see another image in gallery? This is really too long and wrong and user experience is bad. Imagine gallery with lots of items. Users wants to see image, not slow animation. 
Total time (1s) should be reduced to 200ms maybe. 

Please update default animation time.

**Comment by nicolafranchini** [comment]
The issue was closed because I've added that new option and because I also told you where to edit the script before publishing the update if you didn't like that timing, so it has been addressed 2 times. (and it has never been an issue, it's your opinion that 500 + 500 milliseconds are too much, nobody complained about this before)
Since there's that new option, you can set whatever you want, I will NOT change the default animation time.

**Comment by viliusle** [comment]
Understood. This will be my last reply, after that is up to you.

I am not using your library, even I am web developer, reading about UX, but in this case I am just user, who found other sites using your library. And slow animations there are annoying. So I just want your library to have better user experience. That is all.

Some quotes from google search "recommended animation speed". Keep in mind, that in your case it is 1s or 1000ms.

https://valhead.com/2016/05/05/how-fast-should-your-ui-animations-be/
"suggested upper limit for durations is half that at 500ms."

https://uxdesign.cc/the-ultimate-guide-to-proper-use-of-animation-in-ux-10bd98614fa9
Numerous researches have discovered that optimal speed for interface animation is between 200 and 500 ms.

https://ux.stackexchange.com/questions/66604/optimal-duration-for-animating-transitions
 a slower, more-perceivable animation (600ms) is going to feel quite tedious to most of your users.

**p.s. as you see most places suggest not to use more than 500/600ms, You have 1000ms.** I hope you you will reconsider.

**Comment by nicolafranchini** [comment]
Thanks for your feedback, I appreciate. I understand your references, but in my opinion in this case we are talking about 2 different animations: slide out + fade out current item (500ms) and fade in new item (500ms), I wouldn't consider them as one slow animation of 1000ms, because there are 3 actions perceived: out + load + in.
But since maybe I'm wrong, I've added that option so anyone can easily adjust the timings as he prefer, also possibly setting `navSpeed: 0`

**Comment by nicolafranchini** [comment]
*Edit: after this discussion and reviewing the demo you almost convinced me that the interactions are too slow.
I will end up keeping a default 500ms for the slide-out animation, still adjustable with `navSpeed`, but setting 200ms for all the other animations: fade-in item, backdrop, close item. Thanks again.

**Comment by viliusle** [comment]
Few more comments:

- It is not easy to set these things right, you have to spend time on research, testing, that is why most of developers, using your plugin, **will not do it**, so 90% your users will see default animations, what makes it even more important for you to set it right. But keep that setting of course, it will help.
- You start load image only after first image fades out, so users with slow internet will need to wait for fade out, loading, fade in. That can be a lot.
- If all images are already loaded and cached, load time will be 0, so if we have gallery of 61 images, and user will see it all, but if in the end he will remember that image #1 was so amazing, that he must see it again, so he use keyboard button left to go back back back back, can you calculate how many seconds he will take to reach that amazing first image? After 1 minute...
- You can use middle mouse button to open all images in new tabs 1 by 1, switch to first and use middle mouse button to close all these tabs to preview it all. And it can be much faster than using slow lightbox. 
- I don't remember exact numbers, but because there are so much information these days, most users will spend only few seconds on each page on average. Your few animations cycles takes same few seconds...

Sorry for too much text and good luck.

**Comment by nicolafranchini** [comment]
You could check the latest version. Many things changed, including 300ms as default `navSpeed` and new item loading synchronized with exit animation to save some time.

**Comment by viliusle** [comment]
I tested last released version (from releases, not from master):

- first problem, there is no demo.html file inside code, it is very useful for developers, save lots of time.
- why opened image has `max-width: 1200px;` ? it should take space as much as possible until image is original size. I saw, that you can override it, but since it is hard to see this bug, most developers will not do it.
- opened image has few pixels height white border on bottom (missing `display: block;` on image? )
- opening first image and pushing "next" arrow on keyboard will show second image, should be third. I guess this is because slow animation. Very annoying.

About animation: speed is much better, but I would try to reduce animation duration even more. Also last bug (nr. 4) makes is hard to test it.

p.s. very simple demo attached: (remove ".txt")
[demo.html.txt](https://github.com/nicolafranchini/VenoBox/files/7678600/demo.html.txt)

**Comment by nicolafranchini** [comment]
Hi again.

- There are some examples inside the online demo with relative html and js, the script is quite easy to use, I don't like to include useless files inside the repository, I will possibly link some more demos on JSFiddle.
- I opted for 1200px because inline, ajax, videos and iframes don't have anymore a static width, but ok, now the default max-width is 100%.
- Indeeed, it was missing a `display: block`, which is usually included inside the standard css resets.
- The navigation was locked until the end of the item's change, regardless the speed. I've enabled the fast-navigation.
p.s: the demo with 6 grouped images has always been here: https://veno.es/venobox/

**Comment by viliusle** [comment]
So https://veno.es/venobox/ always have latest code, in his case demo is not  needed, unless somebody wants to test old version for comparison. I like latest version much better. 

if you would like to improve UX more, here are few more ideas/issues:

- left/right icons could be larger
- close button could be larger
- progress like 1/7 (also image title) - font size could be larger. You use 12px font size, which is basically minimum. And with your custom font family it is like 11px which should not be used in web at all, unless information is almost useless. Progress information is far from useless...
- 3 icons on bottom distracts a lot, moving it to top right corner could be better. But keep close as last icon of course.

**Comment by nicolafranchini** [comment]
Yes, since the new version still supports also the jQuery initialization I mantain the same project and the homepage always runs the latest version. Older versions are still available here on github, I've left both the releases, VenoBox 2 and Venobox jQuery.

- The active area of arrow icons is 45 x 45 px, the close button (bigger than the old one) is 54x36, considering also the drag/swipe functionality and that you can close the window also clicking on the backdrop I don't want to steal more space to gestures and central content. 
- Same for numbers and title, since they are (IMHO) less important informations, I opted for a minimum acceptable size. They take the same font of the main page, I don't know if is a good idea, or if would be better to set a standard `font-family: Arial, Helvetica, sans-serif;`
- At the end these icons are there because in mobile view if we place navigation numbers + title + socials + close button, there is no enough space for the title, so, since there is the option `titlePosition`, I left the central area top and bottom for title and share: if you have the title on top the socials are on the bottom, if title is on the bottom, socials are on top. You can opt for a `shareStyle: 'transparent'` to remove the background and make them less distractive.

Thanks again for your contribution, it gave me a lot of hint to carry on and renew this project.

**Comment by eyaler** [comment]
+1 for allowing to change title size
