### ISSUE TITLE
closing venobox from script

### ISSUE THREAD

**Issue by dogstar10** [nicolafranchini/VenoBox#32]
hi,
i'd like to be able to close the venobox from jquery... is it possible?

i have an form in a venobox window which submits via ajax and i'd like to close the window once the form has been successfully submitted.

thanks

**Comment by sabaohai** [comment]
Hi, I want to access the closeVbox() instead of triggering the click
```javascript
jQuery('.vbox-close, .vbox-overlay').trigger('click');
```

I want closeVbox() to achieve address bar url update when user viewing and return from iframe. My proposed solution is to trigger the closeVbox() when user clicking the "Back" history button, and trigger "back" history when user click close or overlay.

Thanks!
