### ISSUE TITLE
Jquery Conflict with Venobox

### ISSUE THREAD

**Issue by mosta2** [nicolafranchini/VenoBox#36]
I try to load a div using venobox and inside this div I bound the element to click function as shown in fiddle

http://jsfiddle.net/mosta/gm9yf6vm/

if you click on "Delete" it will show alert but after loading venobox it does not work

Can you tell me how to solve this?
Thanks and appreciate your help
Mostafa

**Comment by nicolafranchini** [comment]
Hi Mostafa, the problem is that when you open the window, the script rewrites you destination div inside the popup as new html, so the click function is not initializated on it.
the solution is to change 
`$(".btnconfirmdelete").click(function ...`
with
`$(document).on('click', '.btnconfirmdelete', function ...`

here the example updated: 
http://jsfiddle.net/gm9yf6vm/2/
